In [ ]:
import numpy as np

In [ ]:
n=int(input("Enter number of resources: "))
print("Enter max instances of each resource- ")
a=int(input("a="))
b=int(input("b="))
c=int(input("c="))

Enter number of resources: 3
Enter max instances of each resource- 
a=10
b=5
c=7


In [ ]:
p=int(input("Enter number of processes: "))
pro=list(range(p))
pro

Enter number of processes: 5


[0, 1, 2, 3, 4]

In [ ]:
print("Enter the allocation matrix: ")
alloc=[]
for i in range(p):
  temp=[]
  for j in range(1,n+1):
    temp.append(int(input(f"P[{i}],R{j}=")))
  alloc.append(temp)
alloc=np.asarray(alloc)
alloc

Enter the allocation matrix: 
P[0],R1=0
P[0],R2=1
P[0],R3=0
P[1],R1=2
P[1],R2=0
P[1],R3=0
P[2],R1=3
P[2],R2=0
P[2],R3=2
P[3],R1=2
P[3],R2=1
P[3],R3=1
P[4],R1=0
P[4],R2=0
P[4],R3=2


array([[0, 1, 0],
       [2, 0, 0],
       [3, 0, 2],
       [2, 1, 1],
       [0, 0, 2]])

In [ ]:
print("Enter the MAX matrix: ")
max=[]
for i in range(p):
  temp=[]
  for j in range(1,n+1):
    temp.append(int(input(f"P[{i}],R{j}=")))
  max.append(temp)
max=np.asarray(max)
max

Enter the MAX matrix: 
P[0],R1=7
P[0],R2=5
P[0],R3=3
P[1],R1=3
P[1],R2=2
P[1],R3=2
P[2],R1=9
P[2],R2=0
P[2],R3=2
P[3],R1=2
P[3],R2=2
P[3],R3=2
P[4],R1=4
P[4],R2=3
P[4],R3=3


array([[7, 5, 3],
       [3, 2, 2],
       [9, 0, 2],
       [2, 2, 2],
       [4, 3, 3]])

In [ ]:
total=np.zeros(n,dtype=int)
for x in alloc:
  total=np.add(total,x)
total

array([7, 2, 5])

In [ ]:
avail=np.subtract(np.array([a,b,c]),total)
print("Available resources: ",avail)

Available resources:  [3 3 2]


In [ ]:
remain=[]
for x,y in zip(alloc,max):
  temp=np.subtract(y,x)
  remain.append(temp)

remain=np.array(remain)
print("Remaining:\n",remain)

Remaining:
 [[7 4 3]
 [1 2 2]
 [6 0 0]
 [0 1 1]
 [4 3 1]]


In [ ]:
def check_avail(pr):
  for i,j in enumerate(pr):
    if(j>avail[i]):
      return 0
  return 1

In [ ]:
i=0
ss=[]
while np.size(remain):
  if(i>len(remain)-1):
    i=0
  if(check_avail(remain[i])==0):
    i+=1
    continue
  else:
    ss.append(pro[i])
    avail=np.add(avail,alloc[i])
    remain=np.delete(remain, i, 0)
    alloc=np.delete(alloc,i,0)
    pro=np.delete(pro,i,0)

In [ ]:
if(len(ss)==p):
  print("Safe sequence: ",ss)
else:
  print("The system is not in safe state.")

Safe sequence:  [1, 3, 4, 0, 2]
